# Generated by Django 6.0 on 2026-01-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces (pcs)'), ('kg', 'Kilogram (kg)'), ('ltr', 'Liter (L)'), ('box', 'Box'), ('m', 'Meter (m)'), ('doz', 'Dozen')], default='pcs', max_length=5),
        ),
    ]
