# Generated by Django 6.0 on 2026-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
