# Generated by Django 6.0 on 2026-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_systemsettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Scan or type the barcode/serial number', max_length=50, null=True, unique=True),
        ),
    ]
